/*
  *
  *   --- THIS FILE GENERATED BY S-FUNCTION BUILDER: 3.0 ---
  *
  *   This file is a wrapper S-function produced by the S-Function
  *   Builder which only recognizes certain fields.  Changes made
  *   outside these fields will be lost the next time the block is
  *   used to load, edit, and resave this file. This file will be overwritten
  *   by the S-function Builder block. If you want to edit this file by hand, 
  *   you must change it only in the area defined as:  
  *
  *        %%%-SFUNWIZ_wrapper_XXXXX_Changes_BEGIN 
  *            Your Changes go here
  *        %%%-SFUNWIZ_wrapper_XXXXXX_Changes_END
  *
  *   For better compatibility with the Real-Time Workshop, the
  *   "wrapper" S-function technique is used.  This is discussed
  *   in the Real-Time Workshop User's Manual in the Chapter titled,
  *   "Wrapper S-functions".
  *
  *   Created: Mon Apr  5 17:29:16 2010
  */


/*
 * Include Files
 *
 */
#if defined(MATLAB_MEX_FILE)
#include "tmwtypes.h"
#include "simstruc_types.h"
#else
#include "rtwtypes.h"
#endif
/* %%%-SFUNWIZ_wrapper_includes_Changes_BEGIN --- EDIT HERE TO _END */
#include <math.h>
/* %%%-SFUNWIZ_wrapper_includes_Changes_END --- EDIT HERE TO _BEGIN */
#define u_width 4
#define y_width 3
/*
 * Create external references here.  
 *
 */
/* %%%-SFUNWIZ_wrapper_externs_Changes_BEGIN --- EDIT HERE TO _END */
/* extern double func(double a); */
/* %%%-SFUNWIZ_wrapper_externs_Changes_END --- EDIT HERE TO _BEGIN */

/*
 * Output functions
 *
 */
void TECslipcont_Outputs_wrapper(const real_T *u,
                          real_T *y, 
                           const real_T  *params, const int_T p_width0)
{
/* %%%-SFUNWIZ_wrapper_Outputs_Changes_BEGIN --- EDIT HERE TO _END */
/* slip limit control */

double s, slimu, sliml, Fx, iS;
double Ts;
double Kt, Ksl;
double sig, S;
double TCSmode;

s=u[0];
slimu=u[1]; /* upper limit */
sliml=u[2]; /* lower limit */
iS=u[3];

Ksl=params[0];
Kt=params[1];

Ts=0.002;

if (s>slimu) {
    TCSmode=2;
    sig=s+Ksl*iS;
    y[0]=Kt*sig;
    S=(slimu-s);
    iS=iS+S*Ts;
}
else if (s<sliml) {
    TCSmode=3;
    sig=s+Ksl*iS;
    y[0]=Kt*sig;
    S=(sliml-s);
    iS=iS+S*Ts;
}
else {
    TCSmode=1;
    y[0]=0;
    S=0.;
    iS=-s/Ksl;
}

y[1]=iS;
y[2]=TCSmode;

/* %%%-SFUNWIZ_wrapper_Outputs_Changes_END --- EDIT HERE TO _BEGIN */
}
