/*
 * File: VEC.c
 *
 *
  *
  *   --- THIS FILE GENERATED BY S-FUNCTION BUILDER: 3.0 ---
  *
  *   This file is an S-function produced by the S-Function
  *   Builder which only recognizes certain fields.  Changes made
  *   outside these fields will be lost the next time the block is
  *   used to load, edit, and resave this file. This file will be overwritten
  *   by the S-function Builder block. If you want to edit this file by hand, 
  *   you must change it only in the area defined as:  
  *
  *        %%%-SFUNWIZ_defines_Changes_BEGIN
  *        #define NAME 'replacement text' 
  *        %%% SFUNWIZ_defines_Changes_END
  *
  *   DO NOT change NAME--Change the 'replacement text' only.
  *
  *   For better compatibility with the Real-Time Workshop, the
  *   "wrapper" S-function technique is used.  This is discussed
  *   in the Real-Time Workshop User's Manual in the Chapter titled,
  *   "Wrapper S-functions".
  *
  *  -------------------------------------------------------------------------
  * | See matlabroot/simulink/src/sfuntmpl_doc.c for a more detailed template |
  *  ------------------------------------------------------------------------- 
 * Created: Mon Apr  5 16:49:19 2010
 * 
 *
 */


#define S_FUNCTION_NAME VEC
#define S_FUNCTION_LEVEL 2
/*<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<*/
/* %%%-SFUNWIZ_defines_Changes_BEGIN --- EDIT HERE TO _END */
#define NUM_INPUTS          1
/* Input Port  0 */
#define IN_PORT_0_NAME      u
#define INPUT_0_WIDTH       12
#define INPUT_DIMS_0_COL    1
#define INPUT_0_DTYPE       real_T
#define INPUT_0_COMPLEX     COMPLEX_NO
#define IN_0_FRAME_BASED    FRAME_NO
#define IN_0_DIMS           1-D
#define INPUT_0_FEEDTHROUGH 1
#define IN_0_ISSIGNED        0
#define IN_0_WORDLENGTH      8
#define IN_0_FIXPOINTSCALING 1
#define IN_0_FRACTIONLENGTH  9
#define IN_0_BIAS            0
#define IN_0_SLOPE           0.125

#define NUM_OUTPUTS          1
/* Output Port  0 */
#define OUT_PORT_0_NAME      y
#define OUTPUT_0_WIDTH       9
#define OUTPUT_DIMS_0_COL    1
#define OUTPUT_0_DTYPE       real_T
#define OUTPUT_0_COMPLEX     COMPLEX_NO
#define OUT_0_FRAME_BASED    FRAME_NO
#define OUT_0_DIMS           1-D
#define OUT_0_ISSIGNED        1
#define OUT_0_WORDLENGTH      8
#define OUT_0_FIXPOINTSCALING 1
#define OUT_0_FRACTIONLENGTH  3
#define OUT_0_BIAS            0
#define OUT_0_SLOPE           0.125

#define NPARAMS              1
/* Parameter  1 */
#define PARAMETER_0_NAME      params
#define PARAMETER_0_DTYPE     real_T
#define PARAMETER_0_COMPLEX   COMPLEX_NO

#define SAMPLE_TIME_0        0.002
#define NUM_DISC_STATES      0
#define DISC_STATES_IC       [0]
#define NUM_CONT_STATES      0
#define CONT_STATES_IC       [0]

#define SFUNWIZ_GENERATE_TLC 0
#define SOURCEFILES "__SFB__"
#define PANELINDEX           9
#define USE_SIMSTRUCT        0
#define SHOW_COMPILE_STEPS   0                   
#define CREATE_DEBUG_MEXFILE 0
#define SAVE_CODE_ONLY       0
#define SFUNWIZ_REVISION     3.0
/* %%%-SFUNWIZ_defines_Changes_END --- EDIT HERE TO _BEGIN */
#include <math.h>
/*<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<*/
#include "simstruc.h"
#define PARAM_DEF0(S) ssGetSFcnParam(S, 0)

#define IS_PARAM_DOUBLE(pVal) (mxIsNumeric(pVal) && !mxIsLogical(pVal) &&\
!mxIsEmpty(pVal) && !mxIsSparse(pVal) && !mxIsComplex(pVal) && mxIsDouble(pVal))

/*====================*
 * S-function methods *
 *====================*/
#define MDL_CHECK_PARAMETERS
 #if defined(MDL_CHECK_PARAMETERS) && defined(MATLAB_MEX_FILE)
   /* Function: mdlCheckParameters =============================================
     * Abstract:
     *    Validate our parameters to verify they are okay.
     */
    static void mdlCheckParameters(SimStruct *S)
    {
     #define PrmNumPos 46
     int paramIndex = 0;
     bool validParam = false;
     char paramVector[] ={'1'};
     static char parameterErrorMsg[] ="The data type and/or complexity of parameter    does not match the information "
     "specified in the S-function Builder dialog. For non-double parameters you will need to cast them using int8, int16,"
     "int32, uint8, uint16, uint32 or boolean."; 

     /* All parameters must match the S-function Builder Dialog */
     

	 {
	  const mxArray *pVal0 = ssGetSFcnParam(S,0);
	  if (!IS_PARAM_DOUBLE(pVal0)) {
	    validParam = true;
	    paramIndex = 0;
	    goto EXIT_POINT;
	  }
	 }
      
     EXIT_POINT:
      if (validParam) {
	  parameterErrorMsg[PrmNumPos] = paramVector[paramIndex];
	  ssSetErrorStatus(S,parameterErrorMsg);
      }
	return;
    }
 #endif /* MDL_CHECK_PARAMETERS */
/* Function: mdlInitializeSizes ===============================================
 * Abstract:
 *   Setup sizes of the various vectors.
 */
static void mdlInitializeSizes(SimStruct *S)
{

    DECL_AND_INIT_DIMSINFO(inputDimsInfo);
    DECL_AND_INIT_DIMSINFO(outputDimsInfo);
    ssSetNumSFcnParams(S, NPARAMS);  /* Number of expected parameters */
      #if defined(MATLAB_MEX_FILE)
	if (ssGetNumSFcnParams(S) == ssGetSFcnParamsCount(S)) {
	  mdlCheckParameters(S);
	  if (ssGetErrorStatus(S) != NULL) {
	    return;
	  }
	 } else {
	   return; /* Parameter mismatch will be reported by Simulink */
	 }
      #endif

    ssSetNumContStates(S, NUM_CONT_STATES);
    ssSetNumDiscStates(S, NUM_DISC_STATES);

    if (!ssSetNumInputPorts(S, NUM_INPUTS)) return;
    ssSetInputPortWidth(S, 0, INPUT_0_WIDTH);
    ssSetInputPortDataType(S, 0, SS_DOUBLE);
    ssSetInputPortComplexSignal(S, 0, INPUT_0_COMPLEX);
    ssSetInputPortDirectFeedThrough(S, 0, INPUT_0_FEEDTHROUGH);
    ssSetInputPortRequiredContiguous(S, 0, 1); /*direct input signal access*/

    if (!ssSetNumOutputPorts(S, NUM_OUTPUTS)) return;
    ssSetOutputPortWidth(S, 0, OUTPUT_0_WIDTH);
    ssSetOutputPortDataType(S, 0, SS_DOUBLE);
    ssSetOutputPortComplexSignal(S, 0, OUTPUT_0_COMPLEX);
    ssSetNumSampleTimes(S, 1);
    ssSetNumRWork(S, 0);
    ssSetNumIWork(S, 0);
    ssSetNumPWork(S, 0);
    ssSetNumModes(S, 0);
    ssSetNumNonsampledZCs(S, 0);

    /* Take care when specifying exception free code - see sfuntmpl_doc.c */
    ssSetOptions(S, (SS_OPTION_EXCEPTION_FREE_CODE |
		     SS_OPTION_WORKS_WITH_CODE_REUSE));
}

#if defined(MATLAB_MEX_FILE)
#define MDL_SET_INPUT_PORT_DIMENSION_INFO
static void mdlSetInputPortDimensionInfo(SimStruct        *S, 
                                         int_T            port,
                                         const DimsInfo_T *dimsInfo)
{
    if(!ssSetInputPortDimensionInfo(S, port, dimsInfo)) return;
}
#endif

#define MDL_SET_OUTPUT_PORT_DIMENSION_INFO
#if defined(MDL_SET_OUTPUT_PORT_DIMENSION_INFO)
static void mdlSetOutputPortDimensionInfo(SimStruct        *S, 
                                          int_T            port, 
                                          const DimsInfo_T *dimsInfo)
{
 if (!ssSetOutputPortDimensionInfo(S, port, dimsInfo)) return;
}
#endif
# define MDL_SET_INPUT_PORT_FRAME_DATA
static void mdlSetInputPortFrameData(SimStruct  *S, 
                                     int_T      port,
                                     Frame_T    frameData)
{
    ssSetInputPortFrameData(S, port, frameData);
}
/* Function: mdlInitializeSampleTimes =========================================
 * Abstract:
 *    Specifiy  the sample time.
 */
static void mdlInitializeSampleTimes(SimStruct *S)
{
    ssSetSampleTime(S, 0, SAMPLE_TIME_0);
    ssSetOffsetTime(S, 0, 0.0);
}

#define MDL_SET_INPUT_PORT_DATA_TYPE
static void mdlSetInputPortDataType(SimStruct *S, int port, DTypeId dType)
{
    ssSetInputPortDataType( S, 0, dType);
}
#define MDL_SET_OUTPUT_PORT_DATA_TYPE
static void mdlSetOutputPortDataType(SimStruct *S, int port, DTypeId dType)
{
    ssSetOutputPortDataType(S, 0, dType);
}

#define MDL_SET_DEFAULT_PORT_DATA_TYPES
static void mdlSetDefaultPortDataTypes(SimStruct *S)
{
  ssSetInputPortDataType( S, 0, SS_DOUBLE);
 ssSetOutputPortDataType(S, 0, SS_DOUBLE);
}
/* Function: mdlOutputs =======================================================
 *
*/

static void mdlOutputs(SimStruct *S, int_T tid)
{
    const real_T   *u  = (const real_T*) ssGetInputPortSignal(S,0);
    real_T        *y  = (real_T *)ssGetOutputPortRealSignal(S,0);
    const int_T   p_width0  = mxGetNumberOfElements(PARAM_DEF0(S));
    const real_T  *params  = mxGetData(PARAM_DEF0(S));

    double beta, r, arlim, aylim, V, VECtype, iS;
double a, b, c, q, K, Ks, Ku;
double pi, Ts;
double upperr, lowerr, upperB, lowerB, upperpr, lowerpr, upperpB, lowerpB;
double a1, b1, a2, b2, xul, xur, xll, xlr,yul,yur,yll,ylr;
double bd, buf, x1, y1, d1, x2, y2, d2;
double Bref, rref, z, zref, Ss, sig;
double VECmode, VECSW;
double startline;
double predictB, predictr, predictV;
double predictSW, BetaSW;

pi=3.141592;
Ts=0.002;

beta=u[0];
r=u[1];
predictB=u[2];
predictr=u[3];
V=u[4];
arlim=u[5];
aylim=u[6]*1.0;
VECtype=u[7];   /* 1:error dynamics, 2:servo */
VECSW=u[8];
predictSW=u[9];
BetaSW=u[10];
iS=u[11];

a=params[0];
b=params[1];
c=params[2];
q=params[3];
K=params[4];
Ks=params[5];
Ku=params[6];

if (beta>(60./180.*pi)) beta=60./180.*pi;
else if (beta<(-60./180.*pi)) beta=-60./180.*pi;

a1=0.; /* slope of yaw rate limit line */
if (BetaSW==0) b=0.; /* if b==0, beta limit control */

upperB=b/V*r+arlim;
lowerB=b/V*r-arlim;
upperr=a1*(beta-(-arlim+b*aylim/V/V))+aylim/V;
lowerr=a1*(beta-(arlim-b*aylim/V/V))-aylim/V;

upperpB=b/V*predictr+arlim;
lowerpB=b/V*predictr-arlim;
upperpr=a1*(predictB-(-arlim+b*aylim/V/V))+aylim/V;
lowerpr=a1*(predictB-(arlim-b*aylim/V/V))-aylim/V;

/* Define control mode */
/* VECmode 1:no control, 2:decrease yaw moment, 3:increase yaw moment */
startline=1.;
if (predictSW==0) {
    if (beta<lowerB*startline) VECmode=2;
    else if (beta>upperB*startline) VECmode=3;
    else if (r>upperr*startline) VECmode=2;
    else if (r<lowerr*startline) VECmode=3;
    else VECmode=1;
}
else {
    if ((predictB<lowerpB)|(beta<lowerB)) VECmode=2;
    else if ((predictB>upperpB)|(beta>upperB)) VECmode=3;
    else if ((predictr>upperpr)|(r>upperr)) VECmode=2;
    else if ((predictr<lowerpr)|(r<lowerr)) VECmode=3;
    else VECmode=1;
}

if (VECSW==0) VECmode=0;

/* Define target states */
if ((VECmode==2)||(VECmode==3)) {
    if (BetaSW==0) {
        xul=-arlim;
        yul=aylim/V;
        xur=arlim;
        yur=a1*(xur-(-arlim))+aylim/V;
        xll=-arlim;
        yll=a1*(xll-(arlim))-aylim/V;
        xlr=arlim;
        ylr=-aylim/V;
    }
    else {
        xul=-arlim+b*aylim/V/V;
        yul=aylim/V;
        xlr=arlim-b*aylim/V/V;
        ylr=-aylim/V;
        /* upper right edge of safe area */
        /* line1: y=a1 x + b1, limit to max ay */
        b1=-a1*(-arlim+b*aylim/V/V)+aylim/V;
        /* line2: y=a2 x + b2, limit to min alpha_r */
        a2=V/b;
        b2=-V*arlim/b;
        xur=(b2-b1)/(a1-a2);
        yur=V/b*(xur-aylim);
        /* lower left edge of safe area */
        /* line1: y=a1 x + b1, limit to min ay */
        b1=-a1*(-arlim+b*(-aylim)/V/V)-aylim/V;
        /* line2: y=a2 x + b2, limit to max alpha_r */
        a2=V/b;
        b2=-V*(-arlim)/b;
        xll=(b2-b1)/(a1-a2);
        yll=V/b*(xll-(-arlim));
    }
    
    /* Calculate target states */
    if (VECmode==2) {
        /* Calculate beta of the closest point on line 1 to current states */
        b1=-a1*(-arlim+b*aylim/V/V)+aylim/V;
        if (a1==0.) buf=beta;
        else {
            bd=r+beta/a1;
            buf=(bd-b1)/(a1+1./a1);
        }
        if (buf>xur) x1=xur; /* Limit beta to safe area */
        else if (buf<xul) x1=xul;
        else x1=buf;
        y1=a1*x1+b1; /* yaw rate of the closest point in safe area to current states */
        d1=(beta-x1)*(beta-x1)+(r-y1)*(r-y1); /* distance between current states and the point */
        
        /* Calculate beta of the closest point on line 2 to current states */
        if (BetaSW==0) {
            x2=-arlim;
            buf=r;
            if (buf>yul) y2=yul;
            else if (buf<yll) y2=yll;
            else y2=buf;
        }
        else {
            a2=V/b;
            b2=-V*(-arlim)/b;
            bd=r+beta/a2;
            buf=(bd-b2)/(a2+1./a2);
            if (buf>xul) x2=xul; /* Limit beta to safe area */
            else if (buf<xll) x2=xll;
            else x2=buf;
            y2=a2*x2+b2; /* yaw rate of the closest point in safe area to current states */
        }
        d2=(beta-x2)*(beta-x2)+(r-y2)*(r-y2); /* distance between current states and the point */
        if (d1<=d2) {
            Bref=x1;
            rref=y1;
        }
        else {
            Bref=x2;
            rref=y2;
        }
    }
    else {
        /* Calculate beta of the closest point on line 1 to current states */
        b1=-a1*(-arlim+b*(-aylim)/V/V)-aylim/V;
        if (a1==0) buf=beta;
        else {
            bd=r+beta/a1;
            buf=(bd-b1)/(a1+1./a1);
        }
        if (buf>xlr) x1=xlr; /* Limit beta to safe area */
        else if (buf<xll) x1=xll;
        else x1=buf;
        y1=a1*x1+b1; /* yaw rate of the closest point in safe area to current states */
        d1=(beta-x1)*(beta-x1)+(r-y1)*(r-y1); /* distance between current states and the point */
        
        /* Calculate beta of the closest point on line 2 to current states */
        if (BetaSW==0) {
            x2=arlim;
            buf=r;
            if (buf>yur) y2=yur;
            else if (buf<ylr) y2=ylr;
            else y2=buf;
        }
        else {
            a2=V/b;
            b2=-V*arlim/b;
            bd=r+beta/a2;
            buf=(bd-b2)/(a2+1./a2);
            if (buf>xur) x2=xur; /* Limit beta to safe area */
            else if (buf<xlr) x2=xlr;
            else x2=buf;
            y2=a2*x2+b2; /* yaw rate of the closest point in safe area to current states */
        }
        d2=(beta-x2)*(beta-x2)+(r-y2)*(r-y2); /* distance between current states and the point */
        if (d1<=d2) {
            Bref=x1;
            rref=y1;
        }
        else {
            Bref=x2;
            rref=y2;
        }
    }
}

/* Calculate control error and control input */
if (VECmode<=1) {
    y[0]=0.;
    Ss=0.;
    if (VECtype==1) iS=0.;
    else iS=-(r-q*beta)/Ks;
}
else {
    if (VECtype==1) {
        z=r-q*beta;
        zref=rref-q*Bref;
        Ss=z-zref;
        sig=Ss+K*iS;
        y[0]=Ku*sig;
        iS=iS+Ss*Ts;
    }
    else {
        z=r-q*beta;
        zref=rref-q*Bref;
        sig=z+Ks*iS;
        y[0]=Ku*sig;
        Ss=zref-z;
        iS=iS+Ss*Ts;
    }
}
y[1]=iS;
y[2]=VECmode;
y[3]=Bref;
y[4]=rref;
y[5]=upperr;
y[6]=lowerr;
y[7]=upperB;
y[8]=lowerB;
}



/* Function: mdlTerminate =====================================================
 * Abstract:
 *    In this function, you should perform any actions that are necessary
 *    at the termination of a simulation.  For example, if memory was
 *    allocated in mdlStart, this is the place to free it.
 */
static void mdlTerminate(SimStruct *S)
{
}

#ifdef  MATLAB_MEX_FILE    /* Is this file being compiled as a MEX-file? */
#include "simulink.c"      /* MEX-file interface mechanism */
#else
#include "cg_sfun.h"       /* Code generation registration function */
#endif


