/*
  *
  *   --- THIS FILE GENERATED BY S-FUNCTION BUILDER: 3.0 ---
  *
  *   This file is a wrapper S-function produced by the S-Function
  *   Builder which only recognizes certain fields.  Changes made
  *   outside these fields will be lost the next time the block is
  *   used to load, edit, and resave this file. This file will be overwritten
  *   by the S-function Builder block. If you want to edit this file by hand, 
  *   you must change it only in the area defined as:  
  *
  *        %%%-SFUNWIZ_wrapper_XXXXX_Changes_BEGIN 
  *            Your Changes go here
  *        %%%-SFUNWIZ_wrapper_XXXXXX_Changes_END
  *
  *   For better compatibility with the Real-Time Workshop, the
  *   "wrapper" S-function technique is used.  This is discussed
  *   in the Real-Time Workshop User's Manual in the Chapter titled,
  *   "Wrapper S-functions".
  *
  *   Created: Mon Apr  5 16:49:19 2010
  */


/*
 * Include Files
 *
 */
#if defined(MATLAB_MEX_FILE)
#include "tmwtypes.h"
#include "simstruc_types.h"
#else
#include "rtwtypes.h"
#endif
/* %%%-SFUNWIZ_wrapper_includes_Changes_BEGIN --- EDIT HERE TO _END */
#include <math.h>
/* %%%-SFUNWIZ_wrapper_includes_Changes_END --- EDIT HERE TO _BEGIN */
#define u_width 9
#define y_width 5
/*
 * Create external references here.  
 *
 */
/* %%%-SFUNWIZ_wrapper_externs_Changes_BEGIN --- EDIT HERE TO _END */
/* extern double func(double a); */

extern double max(double x, double y)
{
if (x>y) return x;
else return y;
}

extern double min(double x, double y)
{
if (x<y) return x;
else return y;
}

/* %%%-SFUNWIZ_wrapper_externs_Changes_END --- EDIT HERE TO _BEGIN */

/*
 * Output functions
 *
 */
void VEC_Outputs_wrapper(const real_T *u,
                          real_T *y, 
                           const real_T  *params, const int_T p_width0)
{
/* %%%-SFUNWIZ_wrapper_Outputs_Changes_BEGIN --- EDIT HERE TO _END */
/* Vehicle envelope control */
/* Limit a yaw rate to aymax/V */
/* Limit a rear tire side slip to grip area */

double beta, r, delta, aflim, arlim, aylim, V, VECtype, iS;
double a, b, c, q, K, Ks, Ku;
double pi, Ts;
double mu, upperr, lowerr, a1, b1, a2, b2, xul, xur, xll, xlr;
double bd, buf, x1, y1, d1, x2, y2, d2;
double Bref, rref, z, zref, S, sig;
double VECmode;

pi=3.141592;
Ts=0.002;

beta=u[0];
r=u[1];
delta=u[2];
aflim=u[3];
arlim=u[4];
aylim=u[5]*1.0;
V=u[6];
VECtype=u[7];   /* 1:error dynamics, 2:servo */
iS=u[8];

a=params[0];
b=params[1];
c=params[2];
q=params[3];
K=params[4];
Ks=params[5];
Ku=params[6];

beta=max(min(beta,60./180.*pi),-60./180.*pi);
delta=max(min(delta,30./180.*pi),-30./180.*pi);
mu=max(min(aylim/9.8,1.),0.1);

upperr=aylim/V;
lowerr=-aylim/V;
upperr=1.*(beta-(b/V*aylim/V-arlim))+aylim/V;
lowerr=1.*(beta-(b/V*(-aylim/V)+arlim))-aylim/V;

/* Define control mode */
/* VECmode 1:no control, 2:decrease yaw moment, 3:increase yaw moment */
if (beta<(b/V*r-arlim)) VECmode=2;
else if (beta>(b/V*r+arlim)) VECmode=3;
else if (r>upperr) VECmode=2;
else if (r<lowerr) VECmode=3;
else VECmode=1;

a1=0.; /* slope of yaw rate limit line */

/* Define target states */
if ((VECmode==2)||(VECmode==3)) {
    /* calculate beta at upper left edge of safe area */
    /* line1: y=a1 x + b1, limit to max ay */
    b1=aylim/V;
    /* line2: y=a2 x + b2, limit to max alpha_r */
    a2=V/b;
    b2=V*arlim/b;
    xul=(b2-b1)/(a1-a2);
    /* beta at upper right edge of safe area */
    /* line1: y=a1 x + b1, limit to max ay */
    b1=aylim/V;
    /* line2: y=a2 x + b2, limit to min alpha_r */
    a2=V/b;
    b2=-V*arlim/b;
    xur=(b2-b1)/(a1-a2);
    /* beta at lower left edge of safe area */
    /* line1: y=a1 x + b1, limit to min ay */
    b1=-aylim/V;
    /* line2: y=a2 x + b2, limit to max alpha_r */
    a2=V/b;
    b2=V*arlim/b;
    xll=(b2-b1)/(a1-a2);
    /* beta at lower right edge of safe area */
    /* line1: y=a1 x + b1, limit to min ay */
    b1=-aylim/V;
    /* line2: y=a2 x + b2, limit to min alpha_r */
    a2=V/b;b2=-V*arlim/b;
    xlr=(b2-b1)/(a1-a2);
    
    /* Calculate target states */
    if (VECmode==2) {
        /* Calculate beta of the closest point on line 1 to current states */
        b1=aylim/V;
        if (a1==0.) buf=beta;
        else {
            bd=r+beta/a1;
            buf=(bd-b1)/(a1+1./a1);
        }
        x1=max(xul,min(xur,buf)); /* Limit beta to safe area */
        y1=a1*x1+b1; /* yaw rate of the closest point in safe area to current states */
        d1=(beta-x1)*(beta-x1)+(r-y1)*(r-y1); /* distance between current states and the point */
        
        /* Calculate beta of the closest point on line 2 to current states */
        a2=V/b;
        b2=V*arlim/b;
        bd=r+beta/a2;
        buf=(bd-b2)/(a2+1./a2);
        x2=max(xll,min(xul,buf)); /* Limit beta to safe area */
        y2=a2*x2+b2; /* yaw rate of the closest point in safe area to current states */
        d2=(beta-x2)*(beta-x2)+(r-y2)*(r-y2); /* distance between current states and the point */
        if (d1<=d2) {
            Bref=x1;
            rref=y1;
        }
        else {
            Bref=x2;
            rref=y2;
        }
    }
    else {
        /* Calculate beta of the closest point on line 1 to current states */
        b1=-aylim/V;
        if (a1==0) buf=beta;
        else {
            bd=r+beta/a1;
            buf=(bd-b1)/(a1+1./a1);
        }
        x1=max(xll,min(xlr,buf)); /* Limit beta to safe area */
        y1=a1*x1+b1; /* yaw rate of the closest point in safe area to current states */
        d1=(beta-x1)*(beta-x1)+(r-y1)*(r-y1); /* distance between current states and the point */
        
        /* Calculate beta of the closest point on line 2 to current states */
        a2=V/b;
        b2=-V*arlim/b;
        bd=r+beta/a2;
        buf=(bd-b2)/(a2+1./a2);
        x2=max(xlr,min(xur,buf)); /* Limit beta to safe area */
        y2=a2*x2+b2; /* yaw rate of the closest point in safe area to current states */
        d2=(beta-x2)*(beta-x2)+(r-y2)*(r-y2); /* distance between current states and the point */
        if (d1<=d2) {
            Bref=x1;
            rref=y1;
        }
        else {
            Bref=x2;
            rref=y2;
        }
    }
}

/* Calculate control error and control input */
if (VECmode==1) {
    y[0]=0.;
    S=0.;
    if (VECtype==1) iS=0.;
    else iS=-(r-q*beta)/Ks;
}
else {
    if (VECtype==1) {
        z=r-q*beta;
        zref=rref-q*Bref;
        S=z-zref;
        sig=S+K*iS;
        y[0]=Ku*sig;
        iS=iS+S*Ts;
    }
    else {
        z=r-q*beta;
        zref=rref-q*Bref;
        sig=z+Ks*iS;
        y[0]=Ku*sig;
        S=zref-z;
        iS=iS+S*Ts;
    }
}
y[1]=iS;
y[2]=VECmode;
y[3]=Bref;
y[4]=rref;

/* %%%-SFUNWIZ_wrapper_Outputs_Changes_END --- EDIT HERE TO _BEGIN */
}
